library(ggplot2)
library(dplyr)
library(gridExtra)
library(DescTools)
library(geodata)
tavg <- worldclim_global("tavg", "10", "worldclim_data/")
precip <- worldclim_global("prec", "10", "worldclim_data/")
dim(tavg)
dim(precip)
